# Generated by Django 5.1.5 on 2025-11-25 07:08

import cloudinary_storage.storage
import proctoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0015_student_department_alter_cheatingaudio_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingaudio',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=proctoring.models.RawCloudinaryStorage(), upload_to='cheating_audios/'),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='cheating_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='student_photos/'),
        ),
    ]
