# Generated by Django 5.1.5 on 2025-12-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0016_alter_cheatingaudio_audio_alter_cheatingimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='completion_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
