# Generated by Django 5.1.5 on 2025-12-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0017_exam_completion_time_exam_end_time_exam_percentile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_name', models.CharField(max_length=50)),
                ('raw_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('performance_level', models.CharField(choices=[('advanced', 'Advanced'), ('proficient', 'Proficient'), ('developing', 'Developing'), ('emerging', 'Emerging'), ('novice', 'Novice')], max_length=20)),
                ('is_strength', models.BooleanField(default=False)),
                ('is_weakness', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='proctoring.exam')),
            ],
            options={
                'ordering': ['-percentage'],
                'unique_together': {('exam', 'competency_name')},
            },
        ),
    ]
