# Generated by Django 5.1.5 on 2025-12-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0018_competencyscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='user_answers',
            field=models.JSONField(default=dict),
        ),
    ]
